-- ============================================================================
-- Testbench: sha_2block_a80_tb
-- Author: Team 14
--
-- Purpose:
--   This testbench verifies that the SHA-256 core can correctly hash a message that spans two 512-bit blocks.
--
--   I did this by having the program hash 80 bytes of ASCII 'a' (0x61) or "a" * 80. The results were compared against a hash generated by my computer
--
--   Since 80 bytes > 64 bytes, SHA-256 padding forces the message to occupy 2 blocks:
--     - Block 0: first 64 bytes of data (all 'a')
--     - Block 1: remaining a's and then padding, then the 64-bit length field (80 bytes * 8 = 640 bits = 0x280)
--     - This padding was put in manually by me.
--
-- What this TB tests:
--   * Multi-block chaining inside sha_256_core where it must take block 0 and then carry the hash state from block 0 to block 1 when the testbench
--     supplies the second block with another data_ready pulse. This is to verify it can take the next block and carry the hash state from block 0 into block 1 correctly.
--
--
--
-- Notes:
--
--   * The ready/accept next block handshake was added to sha_256_core:
--      - ready_for_block is 1 only when the core is IDLE and will begin a new block when data_ready=1 on the next rising edge.
--      - It assigns msg_block_in <= A80_BLOCK0 on the same rising edge where it asserts data_ready <= '1' when ready_for_block=1.
--      - The core captures msg_block_in in READ_MSG_BLOCK (one cycle later) msg_block_in needs to be held stable long enough.
--      - block_done should pulse when the core finishes a block
--
--   This TB does NOT use a fixed wait between block 0 and block 1 anymore.
--   Waits for ready_for_block and then sends the next block.
--   This TB pulses data_ready on the rising edge where ready_for_block='1'
--   Drives msg_block_in on the same edge as data_ready, and holds it stable through the next edge so READ_MSG_BLOCK can capture it
--   Then it forces data_ready back to '0' on the next rising edge (1-cycle pulse)
--   This data_ready back to 0 needs implementeded in whatever wrapper/controller we use to
--   drive our real data.
--
--   This doesn't do streaming.
--
-- OUTPUTS:
--   report note): Computed hash = 0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580
--   report note): Expected hash = 0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580
--   report note): PASS: SHA-256(a*80)
-- ============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.sha_256_pkg.all;
use std.env.all;

entity sha_2block_a80_tb is
end entity;

-- DUT interface signals
architecture sim of sha_2block_a80_tb is
  signal clk             : std_logic := '0';
  signal rst             : std_logic := '1';  -- active high

  -- core inputs
  signal data_ready      : std_logic := '0';  -- start
  signal n_blocks        : natural := 2;      -- Tells core we are sending in two blocks for this test
  signal msg_block_in    : std_logic_vector(0 to 511) := (others => '0'); --512 bit block input (64 bytes)
  
  -- core outputs
  signal ready_for_block : std_logic; 			    -- 1 when core is IDLE and can start next block
  signal block_done      : std_logic; 			    -- pulses when one block is finisehd
  signal finished        : std_logic; 		            -- 1 when ALL of the blocks n_blocks number are processed
  signal data_out        : std_logic_vector(255 downto 0);  -- 256 hash/digest output

-- Test message, a x 80 converted to ASCII
-- *Note: I did not have to split these into two chunks of 32
-- It's just easier to read this way.

-- Block 0 is 0 x 61 repeated 64 times.
-- The x" automatically sends this hex to the core as bits
  constant A80_BLOCK0 : std_logic_vector(0 to 511) :=
    x"6161616161616161616161616161616161616161616161616161616161616161" &  -- 32 bytes
    x"6161616161616161616161616161616161616161616161616161616161616161";   -- 32 bytes

  -- Block 1 has the last 16 bytes of a and then the padding and length field.
  -- Block 1: last 16 'a' bytes, then 0x80, then zeros, then length=640 bits=0x280
  constant A80_BLOCK1 : std_logic_vector(0 to 511) :=
    x"6161616161616161616161616161616180000000000000000000000000000000" &  -- 32 bytes where 16 belongs to a x 80. the 8 after the 61 is something required by sha.
									   -- The first 16 bytes of this block are the last of the a's 0 x 61, the next byte is 0x80
                                                                           -- The rest are zero's and then the length 280
    x"0000000000000000000000000000000000000000000000000000000000000280";   -- 280 is the length, comes from the length of a80 converted to hexadecimal. "a"x80 = 80 × 8 bits/byte = 640 bits.
                                                                           -- Total length must always go in the last 8 bytes of the last block.

  -- This is the expected SHA 256 hash/digest for a x 80. I generated this using the sha in windows powershell
  constant EXPECTED_a80 : std_logic_vector(255 downto 0) :=
    x"0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580";

-- starts
begin
  -- Clock 
  clk <= not clk after 5 ns;

-- Instantiates/connects the sha_256_core
-- Reset value = 1

  dut: entity work.sha_256_core
    generic map (RESET_VALUE => '1')
    port map (
      clk             => clk,
      rst             => rst,
      data_ready      => data_ready,
      n_blocks         => n_blocks,
      msg_block_in     => msg_block_in,
      ready_for_block  => ready_for_block,
      block_done       => block_done,
      finished         => finished,
      data_out         => data_out
    );

  -- The main process that makes this do something

  process
  begin
  
    -- Reset: forces core to reset when re-run testbench. Might need something like this in FSM
  
    rst <= '1';                  -- resets
    data_ready <= '0';
    msg_block_in <= (others => '0');

    wait until rising_edge(clk);
    rst <= '0';

    -- BLOCK 0:
    -- sends block 0 into the core/ drives input
    -- block 0 waits for ready_for_block, then pulse data_ready for 1 clock
  
    wait until rising_edge(clk) and ready_for_block = '1'; -- waits until the core is IDLE and ready

    -- sets msg_block_in = Block 0
    msg_block_in <= A80_BLOCK0;
    data_ready   <= '1';

    wait until rising_edge(clk); -- makes data_ready 0 after one rising edge
    data_ready   <= '0';

    -- This waits for the core to finish processing the first block
    -- Wait for the core to finish this block. Removed for loop with wait cycles, Replaced with this. 
    wait until rising_edge(clk) and block_done = '1';


    -- BLOCK 1: 
    -- repeats the steps of Block zero but passes Block 1 to the core
    -- Sends block 1 in after the wait is over
 
    wait until rising_edge(clk) and ready_for_block = '1';
    msg_block_in <= A80_BLOCK1;
    data_ready   <= '1';

    wait until rising_edge(clk);
    data_ready   <= '0';

    -- Wait for block 1 completion
    wait until rising_edge(clk) and block_done = '1';

  
    -- Done, prints results and checks output against hash
  
    wait until rising_edge(clk) and finished = '1';

    report "Computed hash = " & to_hstring(data_out) severity note;
    report "Expected hash = " & to_hstring(EXPECTED_a80) severity note;

    assert data_out = EXPECTED_a80
      report "FAIL: SHA-256(a*80) mismatch"
      severity failure;

    report "PASS: SHA-256(a*80)" severity note;
    stop;
  end process;

end architecture;
