-- ============================================================================
-- Testbench: sha_2block_a80_tb
-- Author: Team 14
--
-- Purpose:
--   This testbench verifies that the SHA-256 core can correctly hash a message that spans two 512-bit blocks.
--
--   I did this by having the program hash 80 bytes of ASCII 'a' (0x61) or "a" * 80. The results were compared against a hash generated by my computer
--
--   Since 80 bytes > 64 bytes, SHA-256 padding forces the message to occupy 2 blocks:
--     - Block 0: first 64 bytes of data (all 'a')
--     - Block 1: remaining a's and then padding, then the 64-bit length field (80 bytes * 8 = 640 bits = 0x280)
--     - This padding was put in manually by me.
--
-- What this TB tests:
--   * Multi-block chaining inside sha_256_core where it must take block 0 and then carry the hash state from block 0 to block 1 when the testbench
--     supplies the second block with another data_ready pulse. This is to verify it can take the next block and carry the hash state from block 0 into block 1 correctly.
--
-- Notes: the core doesn't seem to have a ready/accept next block handshake. For this TB, I used a fixed wait between block 0 and block 1 to avoid driving the next block too early. For integration, a real handshake might be needed.
-- This doesn't do streaming, it seems like we have to know n_blocks ahead of time
--
-- OUTPUTS:
-- sha_2block_a80_tb.vhd:121:5:@4745ns:(report note): Computed hash = 0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580
-- sha_2block_a80_tb.vhd:122:5:@4745ns:(report note): Expected hash = 0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580
-- sha_2block_a80_tb.vhd:128:5:@4745ns:(report note): PASS: SHA-256(a*80)
-- ============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.sha_256_pkg.all;     

entity sha_2block_a80_tb is
end entity;

-- DUT interface signals
architecture sim of sha_2block_a80_tb is
  signal clk          : std_logic := '0';
  signal rst          : std_logic := '1';  -- active high
  signal data_ready   : std_logic := '0';  -- start
  signal n_blocks     : natural   := 2;    -- Indicates two blocks of txt are being passed
  signal msg_block_in : std_logic_vector(0 to 511) := (others => '0'); --512 bit block input (64 bytes)
  signal finished     : std_logic;         -- Outputs when hash is valid
  signal data_out     : std_logic_vector(255 downto 0);  -- 256 hash/digest output

-- Test message, a x 80 converted to ASCII
-- *Note: I did not have to split these into two chunks of 32
-- It's just easier to read this way.

-- Block 0 is 0 x 61 repeated 64 times.
-- The x" automatically sends this hex to the core as bits
  constant A80_BLOCK0 : std_logic_vector(0 to 511) :=
    x"6161616161616161616161616161616161616161616161616161616161616161" &  -- 32 bytes
    x"6161616161616161616161616161616161616161616161616161616161616161";   -- 32 bytes

-- Block 1 has the last 16 bytes of a and then the padding and length field.

  constant A80_BLOCK1 : std_logic_vector(0 to 511) :=
    x"6161616161616161616161616161616180000000000000000000000000000000" &  -- 32 bytes where 16 belongs to a x 80. the 8 after the 61 is something required by sha. 
-- The first 16 bytes of this block are the last of the a's 0 x 61, the next byte is 0x80
-- The rest are zero's
    x"0000000000000000000000000000000000000000000000000000000000000280"; -- 280 is the length, comes from the length of a80 converted to hexadecimal. "a"x80 = 80 × 8 bits/byte = 640 bits. 
                                                                          -- This is 280 in hex. Length must always go in the last 8 bytes of the last block.

-- This is the expected SHA 256 hash/digest for a x 80. I generated this using the sha in windows powershell
  constant EXP_A80 : std_logic_vector(255 downto 0) :=
    x"0F45E858FBC4176CDF4E411F88281EDEFC390AE5AFE7DF0F44CD9297F0A64580";

-- starts
begin
  clk <= not clk after 5 ns;

-- Instantiates/connects the sha_256_core
-- Reset value = 1

  dut: entity work.sha_256_core
    generic map(RESET_VALUE => '1')
    port map(
      clk          => clk,
      rst          => rst,
      data_ready   => data_ready,
      n_blocks     => n_blocks,
      msg_block_in => msg_block_in,
      finished     => finished,
      data_out     => data_out
    );

-- The main process that makes this do something

  process

-- Makes this wait between sending block 0 and block 1
-- This gives the core time to process a block after data_ready pulse. Probably need a ready for next block signal later to prevent a block from getting put in too soon.

    constant WAIT_CYCLES_PER_BLOCK : integer := 260;
  begin
    rst <= '1';                  -- resets
    wait for 100 ns;
    rst <= '0';
    wait until rising_edge(clk);

-- sends block 0 into the core/ drives input
    msg_block_in <= A80_BLOCK0;
    data_ready <= '1';
    wait until rising_edge(clk);
    data_ready <= '0';

-- This waits for the core to finish processing the first block
    for i in 0 to WAIT_CYCLES_PER_BLOCK loop
      wait until rising_edge(clk);
    end loop;

-- Sends block 1 in after the wait is over
    msg_block_in <= A80_BLOCK1;
    data_ready <= '1';
    wait until rising_edge(clk);
    data_ready <= '0';

-- waits for both blocks to be complete and the final hash is produced
    while finished /= '1' loop
      wait until rising_edge(clk);
    end loop;

-- prints results and checks match
    report "Computed hash = " & to_hstring(data_out) severity note;
    report "Expected hash = " & to_hstring(EXP_A80) severity note;

    assert data_out = EXP_A80
      report "FAIL: SHA-256(a*80) mismatch"
      severity failure;

    report "PASS: SHA-256(a*80)" severity note;
    wait;
  end process;

end architecture;
